from importlib.machinery import SourceFileLoader

import pytest
from pytest_cookies.plugin import Cookies


VERSION = """# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.1.dev0+d20220612'
version_tuple = (0, 1, 'dev0', 'd20220612')
"""


@pytest.fixture
def project(cookies, tmp_path, _cookiecutter_config_file):
    p = tmp_path / "project"
    p.mkdir()
    c = Cookies(str(pytest.cookie_template), tmp_path, _cookiecutter_config_file)
    c._new_output_dir = lambda: str(p)
    c.bake()
    version = p / "project_name" / "src" / "project_name" / "_version.py"
    version.write_text(VERSION)
    return version.parent


def test_cli(project):
    """Test that cli includes subcommands from nbis_project_admin and project"""
    module = SourceFileLoader(  # noqa: F841
        fullname="project_name", path=str(project / "__init__.py")
    ).load_module()
