name: CI

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    defaults:
      run:
        shell: bash -l {0}  # a login shell is required for conda activation
    steps:
      - uses: actions/checkout@v2
      - name: Install depedencies
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter pytest pytest-cookies pytest-runner pytest-cov tox tox-gh-actions
      - name: Run tests
        run: pytest
      - name: Run tox
